### ISSUE TITLE
:bad-arglists linter trips on store specs

### ISSUE THREAD

**Issue by lvh** [lvh/icecap#26]
It's not quite clear if this is a bug in test.check, eastwood, or icecap. It's *probably* not icecap, but our linter is complaining, hence this ticket.

Here's a link to a travis build demonstrating the problem: https://travis-ci.org/lvh/icecap/jobs/36042714#L1426

This is being discussed on jonase/eastwood#51 as well.

**Comment by jafingerhut** [comment]
I haven't been able to reproduce this warning with icecap, but try out Eastwood 0.2.2 if you have not already, and see if it eliminates the :bad-arglists warnings you have been seeing.

**Comment by lvh** [comment]
Yep! Thanks @jafingerhut!
